name: Deploy CUDA Python Docker Image
on:
  push:
    braches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cuda: "11.8.0"
            python: "3.10.10"
            ubuntu: "22.04"
            cudnn: "8"
            root_password: "root"
            get_pip_url: "https://bootstrap.pypa.io/get-pip.py"
            tags: ghcr.io/mjun0812/cuda1180-python31010-server:latest
          - cuda: "11.3.1"
            python: "3.10.10"
            ubuntu: "20.04"
            cudnn: "8"
            root_password: "root"
            get_pip_url: "https://bootstrap.pypa.io/get-pip.py"
            tags: ghcr.io/mjun0812/cuda1131-python31010-server:latest
          - cuda: "10.2"
            python: "3.8.16"
            ubuntu: "18.04"
            cudnn: "8"
            root_password: "root"
            get_pip_url: "https://bootstrap.pypa.io/get-pip.py"
            tags: ghcr.io/mjun0812/cuda102-python3816-server:latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "./cuda_python/"
          build-args:
            - PYTHON=${{ matrix.python }}
            - CUDA_VERSION=${{ matrix.cuda }}
            - CUDNN=${{ matrix.cudnn }}
            - UBUNTU=${{ matrix.ubuntu }}
            - ROOT_PASSWORD=${{ matrix.root_password }}
            - GET_PIP_URL=${{ matrix.get_pip_url }}
          push: true
          tags: ${{ matrix.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
